version: '3.8'

services:
  backend:
    # Берем Dockerfile из каталога stocks_products
    build: ./stocks_products
    # Запускаем сервер gunicorn
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    # Открываем порт 8000 внутри и снаружи
    expose:
      - 8000:8000
    # Подключаем статические и медиа файлы
    volumes:
      - static_volume:/root/backend/
      - media_volume:/root/backend/
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.prod
    # Дожидаемся запуска контейнера db
    depends_on:
      - postgres
  postgres:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:13.0-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/root/backend/
      - media_volume:/root/backend/
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres_volume:
  static_volume:
  media_volume: