version: '3.8'

services:
  backend:
    # Берем Dockerfile из каталога stocks_products
    build: ./stocks_products
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    # куда будут помещены данные из каталога stocks_products
    volumes:
      - ./stocks_products/:/usr/src/stocks_products/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.dev
  postgres:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:13.0-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      # Учетные данные, которые можно будет переопределить
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=netology_stocks_products

volumes:
    postgres_volume:
